"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
type Mode="login"|"register";
export default function EntrarPage(){
 const [mode,setMode]=useState<Mode>("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);const router=useRouter();
 const changeMode=(next:Mode)=>{setMode(next);setPassword("");setError("");};
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('google')==='erro')queueMicrotask(()=>setError('Não foi possível entrar com o Google. Tente novamente.'));},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setLoading(true);const endpoint=mode==="login"?"/api/auth/login":"/api/auth/register";try{const res=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const data=await res.json();if(!res.ok)setError(data.error||"Ocorreu um erro. Tente novamente.");else{router.replace("/");router.refresh();}}catch{setError("Erro de conexão. Verifique sua internet.");}finally{setLoading(false);}}
 const title=mode==="login"?"Seu espaço financeiro":"Criar nova conta",subtitle=mode==="login"?"Entre com seu e-mail e senha.":"Cadastre-se para salvar seus registros.";
 return <div className="flex flex-col items-center justify-center min-h-screen bg-slate-50 px-4"><div className="p-8 bg-white rounded-xl shadow-md max-w-sm w-full">
  <div className="flex justify-center mb-6"><div className="bg-blue-100 p-3 rounded-xl"><svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/></svg></div></div>
  <h2 className="text-2xl font-bold mb-2 text-center text-slate-900">{title}</h2><p className="text-slate-500 mb-6 text-sm text-center">{subtitle}</p>
  <form onSubmit={submit} className="flex flex-col gap-4"><div><label htmlFor="email" className="text-sm font-medium text-slate-700">Seu e-mail</label><input id="email" autoComplete="email" maxLength={254} type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full border border-slate-300 rounded-lg p-2.5 mt-1 focus:ring-2 focus:ring-blue-500 outline-none" placeholder="seu@email.com" required/></div>
  <div><label htmlFor="password" className="text-sm font-medium text-slate-700">Sua senha</label><input id="password" autoComplete={mode==="login"?"current-password":"new-password"} minLength={mode==="login"?1:8} maxLength={72} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full border border-slate-300 rounded-lg p-2.5 mt-1 focus:ring-2 focus:ring-blue-500 outline-none" placeholder="••••••••" required/></div>
  {mode==="register"&&<p className="text-sm text-slate-500">Use pelo menos 8 caracteres.</p>}{error&&<p role="alert" className="text-red-500 text-sm font-medium text-center">{error}</p>}
  <button type="submit" disabled={loading} className="w-full bg-blue-600 text-white font-medium rounded-lg p-2.5 mt-2 hover:bg-blue-700 disabled:opacity-70">{loading?"Aguarde...":mode==="login"?"Entrar":"Criar conta"}</button></form>
  <><div className="flex items-center gap-3 my-5"><span className="h-px flex-1 bg-slate-200"/><span className="text-xs text-slate-400">OU</span><span className="h-px flex-1 bg-slate-200"/></div><a href="/api/auth/google" className="flex w-full items-center justify-center gap-3 rounded-lg border border-slate-300 bg-white p-2.5 text-sm font-medium text-slate-700 hover:bg-slate-50"><svg className="h-5 w-5" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.4-.18-2.07H12v3.92h5.38a4.6 4.6 0 0 1-2 3.02v2.54h3.24c1.9-1.75 2.98-4.33 2.98-7.41Z"/><path fill="#34A853" d="M12 22c2.7 0 4.98-.9 6.64-2.36l-3.24-2.54c-.9.6-2.05.96-3.4.96-2.61 0-4.82-1.76-5.61-4.13H3.04v2.62A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.39 13.93A6 6 0 0 1 6.08 12c0-.67.12-1.32.31-1.93V7.45H3.04A10 10 0 0 0 2 12c0 1.63.39 3.17 1.04 4.55l3.35-2.62Z"/><path fill="#EA4335" d="M12 5.94c1.47 0 2.78.5 3.82 1.5l2.88-2.88A9.65 9.65 0 0 0 12 2a10 10 0 0 0-8.96 5.45l3.35 2.62C7.18 7.7 9.39 5.94 12 5.94Z"/></svg>Continuar com Google</a></>
  <button disabled={loading} onClick={()=>changeMode(mode==="login"?"register":"login")} className="text-blue-600 text-sm mt-4 w-full text-center hover:underline font-medium">{mode==="login"?"Não tem uma conta? Crie uma":mode==="register"?"Já tem conta? Faça login":"Voltar para o login"}</button>
 </div></div>;
}
