'use client';

import {useState} from 'react';
import {Bell,Check,Download,Landmark,LockKeyhole,Palette,Settings2,Target,Trash2,WalletCards} from 'lucide-react';
import {addMonths,amountAt,money,monthLabel,nextInvoiceMonth,summary,type State,type Goal,type Entry} from '@/lib/finance';

type Format=(value:number)=>string;
const tile='rounded-3xl border border-slate-200 bg-white p-5 sm:p-6';

export function TransactionOverview({totals,rows,mode,fmt,hidden}:{totals:ReturnType<typeof summary>;rows:Entry[];mode:'purchases'|'invoices';fmt:Format;hidden:boolean}){
 const incomes=rows.filter(row=>row.kind==='income').length,expenses=rows.length-incomes;
 const income=mode==='purchases'?rows.filter(row=>row.kind==='income').reduce((sum,row)=>sum+row.total,0):totals.income;
 const expense=mode==='purchases'?rows.filter(row=>row.kind==='expense').reduce((sum,row)=>sum+row.total,0):totals.expense;
 return <div className="mb-5 grid gap-3 sm:grid-cols-3">{[
  [mode==='purchases'?'Entradas registradas':'Entradas previstas',income,`${incomes} lançamento(s) visível(is)`,'#1F9D6F'],
  [mode==='purchases'?'Compras registradas':'Saídas previstas',expense,`${expenses} lançamento(s) visível(is)`,'#E4572E'],
  [mode==='purchases'?'Balanço dos registros':'Saldo projetado',income-expense,'Entradas menos saídas','#818cf8'],
 ].map(([label,value,note,color])=><article className={tile} key={String(label)}><div className="flex items-start justify-between"><p className="text-sm text-slate-500">{label}</p><i className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:String(color)}}/></div><strong className="mt-5 block text-2xl">{fmt(Number(value))}</strong><small className="mt-1 block text-slate-500">{hidden?'Valores ocultos':note}</small></article>)}</div>;
}

export function AccountsOverview({data,invoiceMonthOverride,fmt,hidden}:{data:State;invoiceMonthOverride:string|null;fmt:Format;hidden:boolean}){
 const total=data.accounts.reduce((sum,account)=>sum+account.balance,0);
 const asOf=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
 const cardBill=data.cards.reduce((sum,card)=>sum+data.entries.filter(entry=>entry.cardId===card.id&&entry.kind==='expense').reduce((amount,entry)=>amount+amountAt(entry,invoiceMonthOverride??nextInvoiceMonth(asOf,card.due)),0),0);
 return <div className="mb-5 grid gap-4 lg:grid-cols-[1.2fr_1fr]">
  <section className={tile}><div className="flex items-center gap-2 text-sm text-slate-500"><Landmark size={18}/> Patrimônio informado manualmente</div><strong className="mt-4 block text-3xl">{fmt(total)}</strong><p className="mt-2 max-w-xl text-sm text-slate-500">Soma das contas cadastradas. Não inclui cartões e não é atualizada automaticamente pelos bancos.</p><p className="mt-5 text-sm text-slate-500">{data.accounts.length} conta(s) cadastrada(s)</p></section>
  <section className={tile}><div className="flex items-center gap-2 text-sm text-slate-500"><WalletCards size={18}/> {invoiceMonthOverride?`Faturas de ${monthLabel(invoiceMonthOverride)}`:'Próximas faturas a vencer'}</div><strong className="mt-4 block text-3xl">{fmt(cardBill)}</strong><p className="mt-2 text-sm text-slate-500">Compras registradas nos cartões. Pagamentos de fatura não são confirmados pelo banco.</p>{!hidden&&data.cards.length>0&&<div className="mt-4 flex gap-1">{data.cards.map(card=><span key={card.id} title={card.bank} className="h-2 flex-1 rounded-full" style={{backgroundColor:card.color}}/>)}</div>}</section>
 </div>;
}

export function GoalOverview({data,fmt,setView}:{data:State;fmt:Format;setView:(view:'plan')=>void}){
 if(!data.goals.length)return null;
 const target=data.goals.reduce((sum,goal)=>sum+goal.target,0),saved=data.goals.reduce((sum,goal)=>sum+goal.saved,0),pct=target?Math.min(100,Math.round(saved/target*100)):0;
 return <button onClick={()=>setView('plan')} className="flex w-full flex-wrap items-center justify-between gap-4 rounded-3xl bg-[#6C3CE9] p-5 text-left text-white shadow-sm transition hover:translate-y-[-2px] sm:p-6"><div><p className="text-sm text-white/70">Metas financeiras</p><strong className="mt-2 block text-2xl">{fmt(saved)} guardados</strong><p className="mt-1 text-sm text-white/80">{data.goals.length} meta(s) · {pct}% do objetivo total</p></div><span className="grid h-20 w-20 place-items-center rounded-full text-lg font-bold text-[#c4b5fd]" style={{background:`conic-gradient(#c4b5fd ${pct}%,#ffffff3d 0)`,padding:7}}><span className="grid h-full w-full place-items-center rounded-full bg-[#6C3CE9]">{pct}%</span></span></button>;
}

export function GoalsOverview({data,fmt,setModal,save}:{data:State;fmt:Format;setModal:(modal:'goal')=>void;save:(next:State,message?:string)=>Promise<boolean>}){
 const total=data.goals.reduce((sum,goal)=>sum+goal.saved,0),target=data.goals.reduce((sum,goal)=>sum+goal.target,0),pct=target?Math.min(100,Math.round(total/target*100)):0;
 return <div className="mb-6"><section className="flex flex-wrap items-center justify-between gap-4 rounded-3xl bg-[#6C3CE9] p-6 text-white"><div><p className="text-sm text-white/75">Total reservado para metas</p><strong className="mt-2 block text-3xl">{fmt(total)}</strong><p className="mt-2 text-sm text-white/75">{pct}% de {fmt(target)} planejados · valores informados por você</p></div><button onClick={()=>setModal('goal')} className="rounded-xl bg-[#c4b5fd] px-4 py-2.5 text-sm font-semibold text-[#6C3CE9]">+ Criar meta</button></section><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.goals.map((goal:Goal)=>{const progress=goal.target?Math.min(100,Math.round(goal.saved/goal.target*100)):0;return <article className={tile} key={goal.id}><div className="flex items-start justify-between"><Target className="text-[#6C3CE9]"/><button aria-label={`Excluir meta ${goal.name}`} onClick={()=>{if(confirm(`Excluir a meta ${goal.name}?`))void save({...data,goals:data.goals.filter(item=>item.id!==goal.id)},'Meta removida')}} className="text-sm text-slate-500 hover:text-red-600">Excluir</button></div><h3 className="mt-6 font-semibold">{goal.name}</h3><p className="mt-1 text-xs text-slate-500">Até {monthLabel(goal.deadline)}</p><div className="mt-6 flex justify-between gap-2 text-sm"><b>{fmt(goal.saved)}</b><span className="text-slate-500">de {fmt(goal.target)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#6C3CE9]" style={{width:`${progress}%`}}/></div><p className="mt-2 text-xs text-slate-500">{progress}% concluído</p></article>})}</div></div>;
}

export function PeriodReport({data,month,hidden}:{data:State;month:string;hidden:boolean}){
 const months=Array.from({length:6},(_,index)=>addMonths(month,index-5));
 const values=months.map(label=>({label,totals:summary(data,label)}));
 const max=Math.max(1,...values.flatMap(item=>[item.totals.income,item.totals.expense]));
 const avgIncome=values.reduce((sum,item)=>sum+item.totals.income,0)/6,avgExpense=values.reduce((sum,item)=>sum+item.totals.expense,0)/6,savings=avgIncome>0?Math.round((avgIncome-avgExpense)/avgIncome*100):0;
 return <section className={tile}><div><p className="text-sm text-slate-500">Análise do período</p><h2 className="mt-1 text-xl font-semibold">Receitas x despesas · últimos seis meses</h2><p className="mt-1 text-xs text-slate-500">Projeções a partir dos dados cadastrados, sem confirmação bancária.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Renda média',avgIncome],['Gasto médio',avgExpense],['Taxa de economia',savings]].map(([label,value],index)=><div key={String(label)} className="rounded-2xl bg-slate-50 p-4"><p className="text-sm text-slate-500">{label}</p><b className="mt-2 block text-xl">{hidden?'••••':index===2?`${value}%`:money(Number(value))}</b></div>)}</div>{!hidden&&<div className="mt-6 grid h-48 grid-cols-6 items-end gap-2 border-b border-slate-200 sm:gap-5" role="img" aria-label="Comparação mensal de receitas e despesas">{values.map(item=><div key={item.label} className="flex h-full items-end justify-center gap-1"><div className="w-1/3 rounded-t-md bg-[#1F9D6F]" title={`${monthLabel(item.label)}: receitas ${money(item.totals.income)}`} style={{height:`${Math.max(2,item.totals.income/max*100)}%`}}/><div className="w-1/3 rounded-t-md bg-[#E4572E]" title={`${monthLabel(item.label)}: despesas ${money(item.totals.expense)}`} style={{height:`${Math.max(2,item.totals.expense/max*100)}%`}}/></div>)}</div>}<div className="mt-3 grid grid-cols-6 gap-2 text-center text-xs text-slate-500">{months.map(item=><span key={item}>{monthLabel(item).slice(0,3)}</span>)}</div><div className="mt-4 flex gap-5 text-xs text-slate-600"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#1F9D6F]"/>Receitas</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#E4572E]"/>Despesas</span></div><div className="sr-only"><table><caption>Receitas e despesas mensais</caption><tbody>{values.map(item=><tr key={item.label}><th>{monthLabel(item.label)}</th><td>{money(item.totals.income)}</td><td>{money(item.totals.expense)}</td></tr>)}</tbody></table></div></section>;
}

type Theme='light'|'dark'|'system';
export function SettingsPage({theme,setTheme,vaultUser,data,setModal,exportJson,notices,removeCategory}:{theme:Theme;setTheme:(theme:Theme)=>void;vaultUser:string;data:State;setModal:(modal:'settings'|'alerts'|'category'|'offline'|'account')=>void;exportJson:()=>void;notices:unknown[];removeCategory:(name:string)=>void}){
 const [tab,setTab]=useState<'profile'|'preferences'|'notifications'|'categories'|'security'>('preferences');
 const tabs=[['profile','Perfil'],['preferences','Preferências'],['notifications','Notificações'],['categories','Categorias'],['security','Segurança']] as const;
 return <div className="grid gap-5 lg:grid-cols-[220px_1fr]"><nav aria-label="Seções das configurações" className={`${tile} self-start !p-2`}>{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined} className={`block w-full rounded-xl px-4 py-3 text-left text-sm transition ${tab===id?'bg-indigo-50 font-semibold text-[#6C3CE9]':'text-slate-600 hover:bg-slate-50'}`}>{label}</button>)}</nav><section className={tile}>
 {tab==='profile'&&<><h2 className="text-xl font-semibold">Perfil da conta</h2><p className="mt-1 text-sm text-slate-500">Sua identificação de sessão e os dados financeiros configurados.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Identificador da conta</p><b className="mt-1 block break-all text-sm">{vaultUser||'Não disponível'}</b></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Renda mensal configurada</p><b className="mt-1 block">{money(data.salary)}</b></div></div><button className="mt-6 rounded-xl bg-[#6C3CE9] px-4 py-2.5 text-sm font-semibold text-white" onClick={()=>setModal('settings')}>Editar renda e reserva</button><p className="mt-3 text-xs text-slate-500">Nome, foto e telefone ainda não são armazenados pelo Registro Financeiro.</p></>}
 {tab==='preferences'&&<><h2 className="text-xl font-semibold">Preferências gerais</h2><p className="mt-1 text-sm text-slate-500">A identidade roxa do app permanece nos modos claro e escuro.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Modo de cor<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3" value={theme} onChange={event=>setTheme(event.target.value as Theme)}><option value="light">Claro</option><option value="dark">Escuro</option><option value="system">Automático</option></select></label></div><div className="mt-5 flex items-start gap-3 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><Palette size={19} className="shrink-0"/>O modo de cor é salvo neste navegador. Renda e reserva podem ser ajustadas na aba Perfil.</div></>}
 {tab==='notifications'&&<><h2 className="text-xl font-semibold">Avisos e lembretes</h2><p className="mt-1 text-sm text-slate-500">Alertas calculados com os dados registrados no app.</p><p className="mt-6 text-sm">{notices.length} aviso(s) no mês selecionado.</p><button onClick={()=>setModal('alerts')} className="mt-4 flex items-center gap-2 rounded-xl bg-[#6C3CE9] px-4 py-2.5 text-sm font-semibold text-white"><Bell size={17}/>Ver avisos e ativar notificações</button></>}
 {tab==='categories'&&<><h2 className="text-xl font-semibold">Categorias personalizadas</h2><p className="mt-1 text-sm text-slate-500">Use categorias próprias para organizar seus lançamentos.</p><div className="mt-5 flex flex-wrap gap-2">{data.customCategories.length?data.customCategories.map(name=><span key={name} className="inline-flex items-center gap-2 rounded-full bg-slate-100 py-1.5 pl-3 pr-1.5 text-sm">{name}<button type="button" onClick={()=>removeCategory(name)} aria-label={`Remover categoria ${name}`} title={`Remover ${name}`} className="rounded-full p-1 text-slate-500 hover:bg-red-50 hover:text-red-600"><Trash2 size={14}/></button></span>):<p className="text-sm text-slate-500">Nenhuma categoria personalizada.</p>}</div><button onClick={()=>setModal('category')} className="mt-5 rounded-xl bg-[#6C3CE9] px-4 py-2.5 text-sm font-semibold text-white">+ Nova categoria</button></>}
 {tab==='security'&&<><h2 className="text-xl font-semibold">Segurança e dados</h2><p className="mt-1 text-sm text-slate-500">Ações disponíveis para proteger e exportar seus registros.</p><div className="mt-6 space-y-3"><button onClick={()=>setModal('offline')} className="flex w-full items-center justify-between rounded-xl border border-slate-200 p-4 text-left text-sm"><span className="flex items-center gap-3"><LockKeyhole size={19}/>Configurar cópia offline criptografada</span><Settings2 size={17}/></button><button onClick={exportJson} className="flex w-full items-center justify-between rounded-xl border border-slate-200 p-4 text-left text-sm"><span className="flex items-center gap-3"><Download size={19}/>Baixar backup JSON</span><Check size={17}/></button><button onClick={()=>setModal('account')} className="flex w-full items-center justify-between rounded-xl border border-slate-200 p-4 text-left text-sm"><span className="flex items-center gap-3"><LockKeyhole size={19}/>Conta e privacidade</span><Settings2 size={17}/></button></div><p className="mt-5 text-xs text-slate-500">Autenticação em duas etapas e troca de senha dentro do app ainda não estão disponíveis.</p></>}
 </section></div>;
}
