export type PaymentMethod='credit_card'|'pix'|'pix_credit'|'debit_card'|'cash'|'bank_transfer'|'boleto'|'other';
export type Card={id:string;bank:string;name:string;closing:number;due:number;limit:number;color:string};
export type Entry={id:string;name:string;description:string;category:string;date:string;start:string;total:number;installments:number;cardId:string;kind:'expense'|'income';recurring:boolean;method:PaymentMethod;borrower:string;subscription:boolean;tags?:string[];importKey?:string;receiptId?:string;receiptName?:string};
export type Budget={id:string;category:string;limit:number};
export type Goal={id:string;name:string;target:number;saved:number;deadline:string;kind:'goal'|'emergency'};
export type Debt={id:string;name:string;original:number;balance:number;interest:number;installment:number;remaining:number;dueDay:number};
export type State={cards:Card[];entries:Entry[];salary:number;reserve:number;incomeStart:string;paid:string[];budgets:Budget[];goals:Goal[];debts:Debt[];customCategories:string[]};
export const emptyState:State={cards:[],entries:[],salary:0,reserve:50,incomeStart:'2026-09',paid:[],budgets:[],goals:[],debts:[],customCategories:[]};
export const banks:Record<string,string>={'Nubank':'#820ad1','PicPay':'#11c76f','Banco do Brasil':'#f8d117','Caixa Econômica Federal':'#0879c9','Santander':'#ec0000','Itaú':'#ec7000','Bradesco':'#cc092f','Inter':'#ff7a00','C6 Bank':'#242424','BTG Pactual':'#15355e','Mercado Pago':'#00a8e7','Neon':'#00e5b0','Sicredi':'#3fae2a','Sicoob':'#137b43','Banrisul':'#0062a9','Outro':'#5269e7'};
export const categories=['Alimentação','Compras','Casa','Transporte','Saúde','Lazer','Educação','Assinaturas','Impostos','Investimentos','Pets','Outros'];
export const methodLabels:Record<PaymentMethod,string>={credit_card:'Cartão de crédito',pix:'Pix',pix_credit:'Pix Crédito',debit_card:'Cartão de débito',cash:'Dinheiro',bank_transfer:'Transferência',boleto:'Boleto',other:'Outro'};
export function normalizeState(value:Partial<State>):State{return {...emptyState,...value,cards:value.cards??[],entries:(value.entries??[]).map(e=>({...e,method:e.method??(e.cardId?'credit_card':'other'),borrower:e.borrower??'',subscription:e.subscription??(e.recurring&&e.category==='Assinaturas'),tags:e.tags??[],importKey:e.importKey??'',receiptId:e.receiptId??'',receiptName:e.receiptName??''})),budgets:value.budgets??[],goals:value.goals??[],debts:(value.debts??[]).map(debt=>({...debt,original:debt.original??debt.balance})),customCategories:value.customCategories??[]};}
export function monthIndex(s:string){const [y,m]=s.split('-').map(Number);return y*12+m-1;}
export function addMonths(s:string,n:number){const i=monthIndex(s)+n;return `${Math.floor(i/12)}-${String(i%12+1).padStart(2,'0')}`;}
export function firstInvoice(date:string,card:Card){return addMonths(date.slice(0,7),(Number(date.slice(8,10))>=card.closing?1:0)+(card.due<=card.closing?1:0));}
export function amountAt(e:Entry,month:string){const i=monthIndex(month)-monthIndex(e.start);if(i<0||(!e.recurring&&i>=e.installments))return 0;if(e.recurring)return e.total;return Math.floor(e.total/e.installments)+(i<e.total%e.installments?1:0);}
export function summary(s:State,month:string){const income=(month>=s.incomeStart?s.salary:0)+s.entries.filter(e=>e.kind==='income').reduce((a,e)=>a+amountAt(e,month),0);const expense=s.entries.filter(e=>e.kind==='expense').reduce((a,e)=>a+amountAt(e,month),0);return {income,expense,balance:income-expense,investment:Math.round(Math.max(0,income-expense)*s.reserve/100)};}
export const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
export const monthLabel=(s:string)=>new Date(s+'-02T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
export function demoState(month:string):State{return normalizeState({salary:650000,reserve:50,incomeStart:addMonths(month,-6),cards:[{id:'nu',bank:'Nubank',name:'',closing:25,due:5,limit:1200000,color:banks.Nubank},{id:'pp',bank:'PicPay',name:'',closing:20,due:28,limit:600000,color:banks.PicPay}],entries:[{id:'1',name:'Notebook',description:'Compra de exemplo',category:'Educação',date:addMonths(month,-2)+'-10',start:addMonths(month,-2),total:480000,installments:12,cardId:'nu',kind:'expense',recurring:false,method:'credit_card',borrower:'',subscription:false},{id:'2',name:'Pix para aluguel',description:'Despesa mensal',category:'Casa',date:month+'-05',start:month,total:150000,installments:1,cardId:'',kind:'expense',recurring:true,method:'pix',borrower:'',subscription:false},{id:'3',name:'Celular da Ana',description:'Ana usou meu cartão',category:'Compras',date:month+'-08',start:month,total:240000,installments:6,cardId:'nu',kind:'expense',recurring:false,method:'credit_card',borrower:'Ana',subscription:false},{id:'4',name:'Streaming',description:'Assinatura mensal',category:'Assinaturas',date:month+'-12',start:month,total:3990,installments:1,cardId:'pp',kind:'expense',recurring:true,method:'credit_card',borrower:'',subscription:true}],budgets:[{id:'b1',category:'Alimentação',limit:80000},{id:'b2',category:'Lazer',limit:30000}],goals:[{id:'g1',name:'Reserva de emergência',target:1800000,saved:420000,deadline:addMonths(month,18),kind:'emergency'},{id:'g2',name:'Viagem',target:600000,saved:180000,deadline:addMonths(month,10),kind:'goal'}]});}
