export type Card = {id:string;bank:string;name:string;closing:number;due:number;limit:number;color:string};
export type Entry = {id:string;name:string;description:string;category:string;date:string;start:string;total:number;installments:number;cardId:string;kind:'expense'|'income';recurring:boolean};
export type State = {cards:Card[];entries:Entry[];salary:number;reserve:number;incomeStart:string;paid:string[]};
export const emptyState:State={cards:[],entries:[],salary:0,reserve:50,incomeStart:'2026-09',paid:[]};
export const banks:Record<string,string>={'Nubank':'#842bdd','PicPay':'#168a53','Banco do Brasil':'#a3880b','Caixa Econômica Federal':'#1464a3','Santander':'#d32c39','Itaú':'#d96717','Bradesco':'#c93650','Inter':'#e06d20','C6 Bank':'#303843','Outro':'#465ce0'};
export const categories=['Alimentação','Compras','Casa','Transporte','Saúde','Lazer','Educação','Assinaturas','Outros'];
export function monthIndex(s:string){const [y,m]=s.split('-').map(Number);return y*12+m-1;}
export function addMonths(s:string,n:number){const i=monthIndex(s)+n;return `${Math.floor(i/12)}-${String(i%12+1).padStart(2,'0')}`;}
export function firstInvoice(date:string,card:Card){return addMonths(date.slice(0,7),(Number(date.slice(8,10))>=card.closing?1:0)+(card.due<=card.closing?1:0));}
export function amountAt(e:Entry,month:string){const i=monthIndex(month)-monthIndex(e.start);if(i<0||(!e.recurring&&i>=e.installments))return 0;if(e.recurring)return e.total;return Math.floor(e.total/e.installments)+(i<e.total%e.installments?1:0);}
export function summary(s:State,month:string){const income=(month>=s.incomeStart?s.salary:0)+s.entries.filter(e=>e.kind==='income').reduce((a,e)=>a+amountAt(e,month),0);const expense=s.entries.filter(e=>e.kind==='expense').reduce((a,e)=>a+amountAt(e,month),0);return {income,expense,balance:income-expense,investment:Math.round(Math.max(0,income-expense)*s.reserve/100)};}
export const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
export const monthLabel=(s:string)=>new Date(s+'-02T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
export function demoState(month:string):State{return {salary:650000,reserve:50,incomeStart:addMonths(month,-6),paid:[],cards:[{id:'nu',bank:'Nubank',name:'Meu roxinho',closing:25,due:5,limit:1200000,color:banks.Nubank},{id:'pp',bank:'PicPay',name:'Dia a dia',closing:20,due:28,limit:600000,color:banks.PicPay},{id:'bb',bank:'Banco do Brasil',name:'Ourocard',closing:18,due:25,limit:1000000,color:banks['Banco do Brasil']}],entries:[{id:'1',name:'Notebook',description:'Compra de exemplo',category:'Educação',date:addMonths(month,-2)+'-10',start:addMonths(month,-2),total:480000,installments:12,cardId:'nu',kind:'expense',recurring:false},{id:'2',name:'Supermercado',description:'Compra de exemplo',category:'Alimentação',date:month+'-08',start:month,total:68490,installments:1,cardId:'pp',kind:'expense',recurring:false},{id:'3',name:'Sofá',description:'Compra de exemplo',category:'Casa',date:addMonths(month,-4)+'-12',start:addMonths(month,-4),total:360000,installments:10,cardId:'bb',kind:'expense',recurring:false},{id:'4',name:'Aluguel',description:'Despesa de exemplo',category:'Casa',date:addMonths(month,-6)+'-05',start:addMonths(month,-6),total:150000,installments:1,cardId:'',kind:'expense',recurring:true},{id:'5',name:'Academia',description:'Despesa de exemplo',category:'Saúde',date:month+'-02',start:month,total:12990,installments:1,cardId:'nu',kind:'expense',recurring:true}]};}
