'use client';
import type {State} from './finance';

export type OfflineSnapshot={data:State;base:State;revision:string|null;pending:boolean};
type Encrypted={salt:number[];iv:number[];cipher:number[]};
const DB='registro-financeiro-vault',STORE='accounts',LAST='registro-financeiro-vault-user';
function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function record(userId:string){const db=await database();const value=await new Promise<Encrypted|undefined>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).get(userId);request.onsuccess=()=>resolve(request.result as Encrypted|undefined);request.onerror=()=>reject(request.error);});db.close();return value;}
async function key(pin:string,salt:Uint8Array){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:new Uint8Array(salt),iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export function lastVaultUser(){return localStorage.getItem(LAST);}
export async function hasVault(userId:string){return Boolean(await record(userId));}
export async function saveVault(userId:string,pin:string,snapshot:OfflineSnapshot){if(pin.length<8)throw Error('Use uma senha offline de pelo menos 8 caracteres.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const secret=await key(pin,salt);const bytes=new TextEncoder().encode(JSON.stringify(snapshot));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},secret,bytes);const db=await database();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({salt:[...salt],iv:[...iv],cipher:[...new Uint8Array(cipher)]} satisfies Encrypted,userId);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();localStorage.setItem(LAST,userId);}
export async function readVault(userId:string,pin:string){const stored=await record(userId);if(!stored)throw Error('Cópia offline não encontrada.');try{const secret=await key(pin,new Uint8Array(stored.salt));const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(stored.iv)},secret,new Uint8Array(stored.cipher));return JSON.parse(new TextDecoder().decode(bytes)) as OfflineSnapshot;}catch{throw Error('Senha offline incorreta ou cópia danificada.');}}
export async function removeVault(userId:string){const db=await database();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(userId);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();if(localStorage.getItem(LAST)===userId)localStorage.removeItem(LAST);}
