import type {Entry} from './finance';
type Imported=Pick<Entry,'name'|'description'|'date'|'total'|'kind'|'method'>;
const cleanDate=(raw:string)=>{const value=raw.replace(/\D/g,'');if(value.length>=8)return `${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}`;const parts=raw.trim().split(/[\/-]/);if(parts.length===3)return parts[2].length===4?`${parts[2]}-${parts[1].padStart(2,'0')}-${parts[0].padStart(2,'0')}`:`20${parts[2]}-${parts[1].padStart(2,'0')}-${parts[0].padStart(2,'0')}`;return ''};
const method=(text:string)=>/pix/i.test(text)?'pix' as const:/cart[aã]o|debito|débito/i.test(text)?'debit_card' as const:/boleto/i.test(text)?'boleto' as const:'bank_transfer' as const;
export function parseStatement(text:string,fileName:string):Imported[]{if(fileName.toLowerCase().endsWith('.ofx'))return parseOfx(text);return parseCsv(text);}
function parseOfx(text:string){const blocks=text.match(/<STMTTRN>[\s\S]*?<\/STMTTRN>/gi)??text.split(/<STMTTRN>/i).slice(1);return blocks.map(block=>{const get=(tag:string)=>(block.match(new RegExp(`<${tag}>([^<\\r\\n]+)`,'i'))?.[1]||'').trim(),amount=Number(get('TRNAMT').replace(',','.')),name=get('NAME')||get('MEMO')||'Movimentação bancária';return {name,description:get('MEMO'),date:cleanDate(get('DTPOSTED')),total:Math.round(Math.abs(amount)*100),kind:amount>=0?'income' as const:'expense' as const,method:method(name+' '+get('MEMO'))};}).filter(x=>x.date&&x.total>0);}
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),separator=(lines[0]?.match(/;/g)?.length??0)>(lines[0]?.match(/,/g)?.length??0)?';':',';const rows=lines.map(line=>splitCsv(line,separator));const header=rows.shift()?.map(x=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''))??[];const find=(names:string[])=>header.findIndex(h=>names.some(n=>h.includes(n))),dateIndex=find(['data','date']),nameIndex=find(['descricao','historico','description','titulo']),amountIndex=find(['valor','amount']),typeIndex=find(['tipo','natureza']);return rows.map(row=>{let raw=(row[amountIndex]||'').replace(/[^\d,.-]/g,'');if(raw.includes(',')&&raw.includes('.'))raw=raw.lastIndexOf(',')>raw.lastIndexOf('.')?raw.replaceAll('.','').replace(',','.'):raw.replaceAll(',','');else raw=raw.replace(',','.');const amount=Number(raw);let kind:Imported['kind']=amount<0?'expense':'income';if(typeIndex>=0&&/debito|débito|saida|saída|expense/i.test(row[typeIndex]||''))kind='expense';const name=row[nameIndex]||'Movimentação bancária';return {name,description:'Importado de extrato',date:cleanDate(row[dateIndex]||''),total:Math.round(Math.abs(amount)*100),kind,method:method(name)};}).filter(x=>x.date&&Number.isFinite(x.total)&&x.total>0);}
function splitCsv(line:string,separator:string){const values:string[]=[];let value='',quoted=false;for(const char of line){if(char==='"')quoted=!quoted;else if(char===separator&&!quoted){values.push(value.trim());value='';}else value+=char;}values.push(value.trim());return values;}

